---
apiVersion: v1
kind: Service
metadata:
  name: lab-app-java-svc
  namespace: default
  labels:
    app: lab-app-java
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8080
  selector:
    app: lab-app-java
  type: LoadBalancer
