---
apiVersion: v1
kind: Service
metadata:
  name: lab-app-java-svc
  labels:
    app: lab-app-java
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8080
  selector:
    app: lab-app-java
    type: LoadBalancer
